name: Release and Publish

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    uses: Orbitary/Convention/.github/workflows/publish.yml@main
    with:
      modules: "api,minecraft/fabric,minecraft/paper/bundle,minecraft/velocity/bundle"
      gradleGroup: "xyz.orbitary.bits"
    secrets: inherit